---
output:
  html_document:
    self_contained: false
    lib_dir: "../site/document/libs"
    includes:
      in_header: "../site/head.html"
      before_body: "../site/navbar.html"
params:
  document: "Journal de Guienne"
  document_subtitle: "Wednesday, September 01, 1784"
  document_id: 1
title: "`r params$document`"
subtitle: "`r params$document_subtitle`"


---

```{r setup, include=FALSE}
library(tidyverse)
library(DT)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)

documents <- read_csv("../data/processed/db_tables/document.csv")
venues <- read_csv("../data/processed/db_tables/venue.csv")
performances <- read_csv("../data/processed/db_tables/performance.csv", col_types = "cnDccccccc")
works <- read_csv("../data/processed/db_tables/work.csv", col_types = "ncccccc")
titles <- read_csv("../data/processed/db_tables/title.csv")
genres <- read_csv("../data/processed/db_tables/genre.csv")
persons <- read_csv("../data/processed/db_tables/person.csv")
aliases <- read_csv("../data/processed/db_tables/alias.csv")
document_has_venue <- read_csv("../data/processed/db_tables/document_has_venue.csv")
document_has_performance <- read_csv("../data/processed/db_tables/document_has_performance.csv")
performance_has_work <- read_csv("../data/processed/db_tables/performance_has_work.csv")
person_has_alias <- read_csv("../data/processed/db_tables/person_has_alias.csv")
person_has_performance <- read_csv("../data/processed/db_tables/person_has_performance.csv")
work_has_title <- read_csv("../data/processed/db_tables/work_has_title.csv")
work_has_person <- read_csv("../data/processed/db_tables/work_has_person.csv")
work_has_genre <- read_csv("../data/processed/db_tables/work_has_genre.csv")

```

```{r}
doc_info <- documents %>%
  filter(doc_id == params$document_id)
```

# Original Document
[`r doc_info$journal_title[1]`](`r doc_info$links[1]`)

# Performances
```{r}
perf <- doc_info %>%
  left_join(document_has_performance, by = "doc_id") %>%
  left_join(performances, by = c("date", "performance_id")) %>%
  left_join(performance_has_work, by = "performance_id") %>%
  left_join(works, by = "work_id") %>%
  left_join(titles, by = "title_id") %>%
  left_join(venues, by = "venue_id") %>%
  mutate(
    perf_link = ifelse(!is.na(performance_id), paste0("<a href='../performance/", performance_id, ".html'>Performance</a>"), ""),
    work_link = ifelse(!is.na(work_id), paste0("<a href='../work/", work_id, ".html'>", work, "</a>"), ""),
    venue_link = ifelse(!is.na(venue_id), paste0("<a href='../venue/", venue_id, ".html'>", venue, "</a>"), "")
  ) %>%
  select(
    Date = date,
    Venue = venue_link,
    `Link to Performance` = perf_link,
    Work = work_link,
    `Work Advertised as` = title
  )

datatable(perf, escape = FALSE)
```

# People
```{r}
people <- doc_info %>%
  left_join(document_has_performance, by = "doc_id") %>%
  left_join(performances, by = c("date", "performance_id")) %>%
  left_join(person_has_performance, by = "performance_id") %>%
  left_join(aliases, by = "alias_id") %>%
  left_join(persons, by = "person_id") %>%
  left_join(works, by = "work_id") %>%
  filter(!is.na(person_id)) %>%
  mutate(
    person_link = ifelse(!is.na(person_id), paste0("<a href='../person/", person_id, ".html'>", person, "</a>"), ""),
    perf_link = ifelse(!is.na(performance_id), paste0("<a href='../performance/", performance_id, ".html'>Performance</a>"), ""),
    work_link = ifelse(!is.na(work_id), paste0("<a href='../work/", work_id, ".html'>", work, "</a>"), "")
  ) %>%
  select(
    `Link to Performance` = perf_link,
    Person = person_link,
    `Credited as` = alias,
    Work = work_link,
    Role = role,
    Character = char_role
  ) %>%
  mutate(Character = ifelse(is.na(Character), "", Character),
         Role = Role)

datatable(people, escape = FALSE)
```
